apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dndfourplayer-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: dnd.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dndfourplayer-svc
                port:
                  number: 8080
